minor fixes with start/stop scripts

diff --git a/service/start_service b/service/start_service
--- a/service/start_service
+++ b/service/start_service
@@ -52,7 +52,7 @@ elif [ -n "$USER_NAME" ] && [ -n "$USER_PASSWD" ] && [ "$SHOCK_AUTH" == "basic" 
 elif [ -n "$USER_TOKEN" ] && [ "$SHOCK_AUTH" == "oauth" ]; then
     SHOCK_CONFIG="$SHOCK_CONFIG --ShockNotebookManager.user_token=$USER_TOKEN --ShockNotebookManager.oauth_url=$OAUTH_USER_URL"
 else
-    echo "Invalid combination of Shock Auth type and Auth credintals\nIf SHOCK_AUTH is 'basic' include USER_NAME and USER_PASSWD\nIf SHOCK_AUTH is 'oauth' include USER_TOKEN."
+    echo "Invalid combination of Shock Auth type and Auth credintals\nIf SHOCK_AUTH is 'basic' include USER_NAME and USER_PASSWD\nIf SHOCK_AUTH is 'oauth' include USER_TOKEN." 1>&2
     exit 1
 fi
 
